// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"




UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Look);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Move);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Jump);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Crouch);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Uncrouch);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_Primary);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_Secondary);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_Melee);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_Spike);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_BasicFirst);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_BasicSecond);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_Signature);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_ActivateSlot_Ultimate);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameEvent_Damaged);


UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Property_SlotIndex);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_OperationValue_SlotIndex);


UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Property_Weapon_Bullet);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Property_Weapon_MagazineBullet);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Property_Weapon_MaxBulletPerMagazine);


