name: PR Checks for Develop

on:
  pull_request:
    branches:
      - develop

env:
  ENGINE_PATH: C:\Program Files\Epic Games\UE_5.5
  PROJECT_NAME: Gunner
  PROJECT_FILENAME: Gunner.uproject
  PLATFORM: Win64
  CONFIGURATION_DEVELOPMENT: Development

jobs:
  build_pr_development_targets:
    name: Build Dev Editor & Dev Game
    runs-on: self-hosted

    steps:
      - name: Mark workspace directory as safe
        shell: powershell
        run: |
          $workspacePath = "${{ github.workspace }}".Replace('\', '/')
          Write-Host "Adding $workspacePath to git safe.directory"
          git config --global --add safe.directory "$workspacePath"
      
      - name: Checkout repository source code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Compile ShaderCompileWorker (Development)
        shell: powershell
        run: |
          Write-Host "Building ShaderCompileWorker (${{ env.CONFIGURATION_DEVELOPMENT }})..."
          Write-Host "Engine Path: ${{ env.ENGINE_PATH }}"
          Write-Host "Project File Path: ${{ github.workspace }}\${{ env.PROJECT_FILENAME }}"
          & "${{ env.ENGINE_PATH }}\Engine\Build\BatchFiles\Build.bat" ShaderCompileWorker ${{ env.PLATFORM }} ${{ env.CONFIGURATION_DEVELOPMENT }} -Project "${{ github.workspace }}\${{ env.PROJECT_FILENAME }}" -Quiet -WaitMutex -FromMSBuild

      - name: Compile Editor (Development)
        shell: powershell
        run: |
          Write-Host "Building ${{ env.PROJECT_NAME }}Editor (${{ env.CONFIGURATION_DEVELOPMENT }})..."
          Write-Host "Engine Path: ${{ env.ENGINE_PATH }}"
          Write-Host "Project File Path: ${{ github.workspace }}\${{ env.PROJECT_FILENAME }}"
          & "${{ env.ENGINE_PATH }}\Engine\Build\BatchFiles\Build.bat" ${{ env.PROJECT_NAME }}Editor ${{ env.PLATFORM }} ${{ env.CONFIGURATION_DEVELOPMENT }} -Project "${{ github.workspace }}\${{ env.PROJECT_FILENAME }}" -Quiet -WaitMutex -FromMSBuild

      - name: Compile Game (Development)
        shell: powershell
        run: |
          Write-Host "Building ${{ env.PROJECT_NAME }} Game (${{ env.CONFIGURATION_DEVELOPMENT }})..."
          Write-Host "Engine Path: ${{ env.ENGINE_PATH }}"
          Write-Host "Project File Path: ${{ github.workspace }}\${{ env.PROJECT_FILENAME }}"
          & "${{ env.ENGINE_PATH }}\Engine\Build\BatchFiles\Build.bat" ${{ env.PROJECT_NAME }} ${{ env.PLATFORM }} ${{ env.CONFIGURATION_DEVELOPMENT }} -Project "${{ github.workspace }}\${{ env.PROJECT_FILENAME }}" -Quiet -WaitMutex -FromMSBuild
